# Start
***
### Machine learning: The problem setting
A learning problem reviews a set of n tests of data and then attempts to predict unknown data as to the name Machine Learning. It learns as it goes and gets smarter everytime it runs a differnt peice of code.
If each test is more than a single integer such as an array of numbers it has multiple attributes.
- Supervissed learning: is when we have data with additional attributes and we want to predict them.
 - Classification: is a problem of id'ing which list an study belongs to. One way to think of this is having a discrte way of way of supervised learning and one only has a certain amount of categories, and for each N sample that is given has to put them in the right place.
  - Regression: if the output is the same then we have run into regression. An example of this is when you try to predict something it wont give the right answer or give the same answer everytime.
- Unsupervised learning: the training data that is used is a set of input vectors and having no similar target values. The aim is to have some problems and have them find the same examples in the dataset. This is called clustering.
***

### Loading an example dataset.

[Scikit-Learn](https://scikit-learn.org/stable/tutorial/index.html) comes with some standard datasets for example iris and digits for classification and the [diabetes dataset](https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html)

In [2]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

A Dataset is an object that acts in a dictonary-like way and has some data and metadata. This is all stored in the .data member, which are two different arrays called samples and features. With using the supervised problem response vars are stored in the .target memeber.

In [3]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [4]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

**digits.data** gives you digits samples and **digits.target** gives you true values of the dataset,

In [5]:
digits.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

The way the data is shown is always in a 2D array. The shape of the array is (samples,features). The inital data mey take a different shape but in the case of the way the digits each inital sample image shape is an 8*8 array.

***
### Learning and predicting
Using the digits dataset, There is samples of each of the 10 possible classes on where we can fit an **estimator**(which is a rule for calculating an estimate of given quantity based on observed data) to predict unseen samples.

But in scikit-learn, an estimator for grouping is a Python object that implements the methods fit() and predict()

An example of the use of estimator is sklearn.svm.SVC, which applies support for vector classification. The estimators constructor takes the models parameters as arguments.

In [6]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100.)

**clf** (classifier) estimator instance is the first thing added to the model and must learn from it. 
This is done by passing it to the fit method. With the training set, we use all but the last image in the dataset which we use to do our predicting.

In [7]:
clf.fit(digits.data[:-1], digits.target[:-1])
svm.SVC(C=100.0, gamma=0.001)

SVC(C=100.0, gamma=0.001)

Now we can predict new values, in this instance we use the last image to do the work for use using digits.data. 

In [8]:
clf.predict(digits.data[-1:])


array([8])

***
### Conventions

Estimators follow rules that make their behavior more predictive.

##### Type casting
- Unless told otherwise, input will be cast to foat64:

In [9]:
# importing needed libraries
import numpy as np
from sklearn import random_projection

rng = np.random.RandomState(0)
X = rng.rand(10, 2000)
X = np.array(X, dtype='float32')
X.dtype

dtype('float32')

The snippent of code above shows that dtype is a float32 but is cast to a float64. Regression targets are cast to float64.

In [13]:
# importing needed libraries
from sklearn import datasets
from sklearn.svm import SVC

#setting variables.
iris = datasets.load_iris()
clf = SVC()
clf.fit(iris.data, iris.target)

list(clf.predict(iris.data[:3]))

[0, 0, 0]

In [14]:
clf.fit(iris.data, iris.target_names[iris.target])

SVC()

In [15]:
list(clf.predict(iris.data[:3]))

['setosa', 'setosa', 'setosa']

 - with using **fit()** it will return an integer array, But with using **predict()** you will get back a string array. This shows the different uses between the two and in what way to use them.

***
### Refitting and updating parameters.

- In the code below we will be using **set_params()** method instead of using fit() multiple times as it would just overrite what is needed.

In [20]:
# importing libraries
import numpy as np
from sklearn.datasets import load_iris

# setting vars
X,y = load_iris(return_X_y=True)

clf = SVC()
clf.set_params(kernel='linear').fit(X, y)

SVC(kernel='linear')

In [21]:
clf.predict(X[:5])

array([0, 0, 0, 0, 0])

In [22]:
clf.set_params(kernel='rbf').fit(X, y)

SVC()

In [23]:
clf.predict(X[:5])

array([0, 0, 0, 0, 0])

In the snippets above rbf kernel is change to linear from using **SVC.set_params** after it has been set in the constructor and is then changed back to rbf to refit the esitmator so it can make another prediction but it comes back with he same answer.

***
### Multiclass vs. multilabel fitting

- With using multiclass classifiers, learning and predictions is all down to how the format of the way the data is fit 

***
# End